import { Montserrat } from 'next/font/google'
import "funuicss/css/fun.css"
import "./assets/css/globals.css"
const font = Montserrat({
  subsets: ["cyrillic"] ,
 weight: ['400', '700' , '100', '200' , '300' , '500' , '900' , '800'] 
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={font.className}>
      <body className={font.className}>{children}</body>
    </html>
  )
}
